name: Update FAQs from Reddit

on: push

jobs:
  update-faqs:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Update faq.md file in the repository
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      - name: Update faq.md
        run: |
          python tools/update_faq_markdown.py --client-id '${{ secrets.REDDIT_CLIENT_ID }}' --client-secret '${{ secrets.REDDIT_CLIENT_SECRET }}' --user-agent '${{ secrets.REDDIT_USER_AGENT }}' \

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update FAQs from Reddit
          commit_options: '--no-verify --signoff'